export const ZivyCoinFactoryABI = [
    {
        inputs: [{ internalType: "address", name: "usdtToken_", type: "address" }],
        stateMutability: "nonpayable",
        type: "constructor",
    },
    {
        anonymous: false,
        inputs: [
            { indexed: true, internalType: "address", name: "expert", type: "address" },
            { indexed: true, internalType: "address", name: "coinAddress", type: "address" },
            { indexed: false, internalType: "string", name: "name", type: "string" },
            { indexed: false, internalType: "string", name: "symbol", type: "string" },
        ],
        name: "CoinLaunched",
        type: "event",
    },
    {
        anonymous: false,
        inputs: [
            { indexed: true, internalType: "address", name: "buyer", type: "address" },
            { indexed: true, internalType: "address", name: "coinAddress", type: "address" },
            { indexed: false, internalType: "uint256", name: "coinAmount", type: "uint256" },
            { indexed: false, internalType: "uint256", name: "usdtAmount", type: "uint256" },
        ],
        name: "CoinsPurchased",
        type: "event",
    },
    {
        anonymous: false,
        inputs: [
            { indexed: true, internalType: "address", name: "spender", type: "address" },
            { indexed: true, internalType: "address", name: "coinAddress", type: "address" },
            { indexed: false, internalType: "uint256", name: "coinAmount", type: "uint256" },
            { indexed: false, internalType: "string", name: "interactionType", type: "string" },
            { indexed: false, internalType: "uint256", name: "expertPayout", type: "uint256" },
            { indexed: false, internalType: "uint256", name: "platformFee", type: "uint256" },
        ],
        name: "CoinsSpent",
        type: "event",
    },
    {
        anonymous: false,
        inputs: [
            { indexed: true, internalType: "address", name: "oldOwner", type: "address" },
            { indexed: true, internalType: "address", name: "newOwner", type: "address" },
        ],
        name: "OwnershipTransferred",
        type: "event",
    },
    {
        anonymous: false,
        inputs: [
            { indexed: false, internalType: "uint256", name: "oldFeeBps", type: "uint256" },
            { indexed: false, internalType: "uint256", name: "newFeeBps", type: "uint256" },
        ],
        name: "PlatformFeeUpdated",
        type: "event",
    },
    {
        inputs: [],
        name: "MAX_FEE_BPS",
        outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
        stateMutability: "view",
        type: "function",
    },
    {
        inputs: [{ internalType: "uint256", name: "", type: "uint256" }],
        name: "allCoins",
        outputs: [{ internalType: "address", name: "", type: "address" }],
        stateMutability: "view",
        type: "function",
    },
    {
        inputs: [{ internalType: "address", name: "", type: "address" }],
        name: "coinExpert",
        outputs: [{ internalType: "address", name: "", type: "address" }],
        stateMutability: "view",
        type: "function",
    },
    {
        inputs: [{ internalType: "address", name: "", type: "address" }],
        name: "expertCoin",
        outputs: [{ internalType: "address", name: "", type: "address" }],
        stateMutability: "view",
        type: "function",
    },
    {
        inputs: [{ internalType: "address", name: "expert", type: "address" }],
        name: "getCoinByExpert",
        outputs: [{ internalType: "address", name: "", type: "address" }],
        stateMutability: "view",
        type: "function",
    },
    {
        inputs: [
            { internalType: "address", name: "coinAddress", type: "address" },
            { internalType: "uint256", name: "coinAmount", type: "uint256" },
        ],
        name: "getUsdtCost",
        outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
        stateMutability: "view",
        type: "function",
    },
    {
        inputs: [
            { internalType: "string", name: "name_", type: "string" },
            { internalType: "string", name: "symbol_", type: "string" },
        ],
        name: "launchCoin",
        outputs: [],
        stateMutability: "nonpayable",
        type: "function",
    },
    {
        inputs: [],
        name: "owner",
        outputs: [{ internalType: "address", name: "", type: "address" }],
        stateMutability: "view",
        type: "function",
    },
    {
        inputs: [],
        name: "platformFeeBps",
        outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
        stateMutability: "view",
        type: "function",
    },
    {
        inputs: [
            { internalType: "address", name: "coinAddress", type: "address" },
            { internalType: "uint256", name: "coinAmount", type: "uint256" },
        ],
        name: "purchaseCoins",
        outputs: [],
        stateMutability: "nonpayable",
        type: "function",
    },
    {
        inputs: [{ internalType: "uint256", name: "newFeeBps", type: "uint256" }],
        name: "setPlatformFee",
        outputs: [],
        stateMutability: "nonpayable",
        type: "function",
    },
    {
        inputs: [
            { internalType: "address", name: "coinAddress", type: "address" },
            { internalType: "address", name: "spender", type: "address" },
            { internalType: "uint256", name: "coinAmount", type: "uint256" },
            { internalType: "string", name: "interactionType", type: "string" },
        ],
        name: "spendCoins",
        outputs: [],
        stateMutability: "nonpayable",
        type: "function",
    },
    {
        inputs: [],
        name: "totalCoinsLaunched",
        outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
        stateMutability: "view",
        type: "function",
    },
    {
        inputs: [{ internalType: "address", name: "newOwner", type: "address" }],
        name: "transferOwnership",
        outputs: [],
        stateMutability: "nonpayable",
        type: "function",
    },
    {
        inputs: [],
        name: "usdtToken",
        outputs: [{ internalType: "address", name: "", type: "address" }],
        stateMutability: "view",
        type: "function",
    },
    {
        inputs: [{ internalType: "address", name: "to", type: "address" }],
        name: "withdrawFees",
        outputs: [],
        stateMutability: "nonpayable",
        type: "function",
    },
] as const;
